import { contributionRegistry } from '@eclipse-docks/core';
import {
  MONACO_GRAMMARS,
  type MonacoGrammarContribution,
} from '@eclipse-docks/extension-monaco-editor/api';

/**
 * ACT-R model highlighting (Monarch).
 * Covers production syntax, buffers, bangs, model forms, and Common Lisp used in tutorials.
 * Token classes map to standard theme scopes (keyword, type, variable, …).
 */
const ACTR_MODEL_FORMS = [
  'clear-all',
  'define-model',
  'sgp',
  'sgp-fct',
  'chunk-type',
  'add-dm',
  'add-dm-fct',
  'define-chunks',
  'define-chunks-fct',
  'goal-focus',
  'goal-focus-fct',
  'p',
  'pp',
  'pp-fct',
  'spp',
  'spp-fct',
  'sdm',
  'sdm-fct',
  'sdp',
  'sdp-fct',
  'dm',
  'dm-fct',
  'set-similarities',
  'set-all-base-levels',
  'set-base-levels',
  'set-visloc-default',
  'set-buffer-chunk',
  'mod-chunk-fct',
  'mod-focus-fct',
  'buffer-read',
  'clear-buffer',
  'declare-buffer-usage',
  'extend-possible-slots',
  'install-device',
  'open-exp-window',
  'close-exp-window',
  'clear-exp-window',
  'add-text-to-exp-window',
  'add-button-to-exp-window',
  'add-line-to-exp-window',
  'remove-items-from-exp-window',
  'modify-line-for-exp-window',
  'start-hand-at-mouse',
  'new-digit-sound',
  'new-tone-sound',
  'run',
  'run-full-time',
  'run-until-condition',
  'run-n-events',
  'reset',
  'reload',
  'model-output',
  'command-output',
  'print-warning',
  'no-output',
  'hide-act-r-output',
  'show-act-r-output',
  'start-echoing-act-r-output',
  'stop-echoing-act-r-output',
  'act-r-random',
  'act-r-noise',
  'mp-time',
  'mp-time-ms',
  'get-time',
  'schedule-event',
  'schedule-event-relative',
  'schedule-event-now',
  'schedule-break',
  'schedule-break-relative',
  'load-act-r-model',
  'add-act-r-command',
  'remove-act-r-command',
  'evaluate-act-r-command',
  'call-act-r-command',
  'monitor-act-r-command',
  'remove-act-r-command-monitor',
  'permute-list',
  'mean-deviation',
  'correlation',
  'visible-virtuals-available',
];

const ACTR_PRODUCTION_KEYWORDS = [
  'isa',
  'cmd',
  'state',
  'buffer',
  'module',
  'request',
  'error',
  'busy',
  'free',
  'full',
  'empty',
  'requested',
  'unrequested',
];

const COMMON_LISP_SPECIALS = [
  'defun',
  'defmacro',
  'defvar',
  'defparameter',
  'defstruct',
  'defpackage',
  'in-package',
  'lambda',
  'let',
  'let*',
  'flet',
  'labels',
  'progn',
  'prog1',
  'prog2',
  'if',
  'when',
  'unless',
  'cond',
  'case',
  'ecase',
  'and',
  'or',
  'not',
  'quote',
  'setf',
  'setq',
  'psetf',
  'incf',
  'decf',
  'push',
  'pushnew',
  'pop',
  'dolist',
  'dotimes',
  'do',
  'do*',
  'loop',
  'return',
  'return-from',
  'block',
  'catch',
  'throw',
  'unwind-protect',
  'handler-case',
  'handler-bind',
  'ignore-errors',
  'eval-when',
  'declare',
  'the',
  'values',
  'multiple-value-bind',
  'multiple-value-list',
  'destructuring-bind',
  'with-open-file',
  'format',
  'print',
  'princ',
  'prin1',
  'terpri',
  'fresh-line',
  'warn',
  'error',
  'load',
  'require',
  'provide',
  'funcall',
  'apply',
  'mapcar',
  'mapcan',
  'maplist',
  'reduce',
  'find',
  'find-if',
  'position',
  'member',
  'assoc',
  'remove',
  'remove-if',
  'remove-if-not',
  'delete',
  'sort',
  'append',
  'nconc',
  'cons',
  'list',
  'list*',
  'length',
  'nth',
  'first',
  'second',
  'third',
  'rest',
  'car',
  'cdr',
  'caar',
  'cadr',
  'cdar',
  'cddr',
  'last',
  'butlast',
  'reverse',
  'nreverse',
  'subseq',
  'copy-list',
  'null',
  'atom',
  'consp',
  'listp',
  'symbolp',
  'numberp',
  'stringp',
  'functionp',
  'eq',
  'eql',
  'equal',
  'equalp',
  'string-equal',
  'string=',
  'string-upcase',
  'string-downcase',
  'concatenate',
  'make-array',
  'make-hash-table',
  'make-list',
  'aref',
  'gethash',
  'remhash',
  'setf',
  'getf',
  'intern',
  'gensym',
  'read',
  'read-from-string',
  'read-line',
  'write-to-string',
  'princ-to-string',
  'parse-integer',
  'floor',
  'ceiling',
  'truncate',
  'round',
  'mod',
  'rem',
  'abs',
  'min',
  'max',
  'sqrt',
  'exp',
  'log',
  'random',
  'zerop',
  'plusp',
  'minusp',
  'evenp',
  'oddp',
  't',
  'nil',
];

const actrLispGrammar: MonacoGrammarContribution = {
  name: 'actr-lisp',
  label: 'ACT-R Lisp',
  extensions: ['.lisp'],
  aliases: ['ACT-R', 'actr-lisp', 'ACT-R Lisp'],
  conf: {
    comments: {
      lineComment: ';;',
      blockComment: ['#|', '|#'],
    },
    brackets: [
      ['(', ')'],
      ['[', ']'],
    ],
    autoClosingPairs: [
      { open: '[', close: ']' },
      { open: '(', close: ')' },
      { open: '"', close: '"' },
    ],
    surroundingPairs: [
      { open: '[', close: ']' },
      { open: '(', close: ')' },
      { open: '"', close: '"' },
    ],
  },
  language: {
    defaultToken: '',
    ignoreCase: true,
    tokenPostfix: '.actr',
    brackets: [
      { open: '(', close: ')', token: 'delimiter.parenthesis' },
      { open: '[', close: ']', token: 'delimiter.square' },
    ],
    modelForms: ACTR_MODEL_FORMS,
    productionKeywords: ACTR_PRODUCTION_KEYWORDS,
    lispSpecials: COMMON_LISP_SPECIALS,
    tokenizer: {
      root: [
        { include: '@whitespace' },
        { include: '@strings' },

        // Production LHS/RHS separator
        [/==>/, 'keyword.operator'],

        // Bang operators: !output! !eval! !bind! !safe-eval!
        [/![a-zA-Z][\w\-]*!/, 'keyword.operator'],

        // Buffer actions: =goal> +retrieval> -goal> ?visual> =visual-location>
        [/[+\-=?][a-zA-Z][\w\-]*\s*>/, 'type'],

        // Production / request variables: =num1 =answer =visual-location
        [/=[a-zA-Z][\w\-]*/, 'variable'],

        // Character / reader macros: #\a #| already handled |# #(
        [/#\\./, 'constant.character'],
        [/#(?:[xXoObB][0-9a-fA-F]+|[\\+-=<>'"&#]\S*)/, 'constant.character'],

        // *special-variables*
        [/\*[^\s(*][^*\s()]*\*/, 'variable.predefined'],

        // :keyword parameters (:esc :lf :trace-detail :attended …)
        [/:[a-zA-Z][\w+\-<>/*&=.?!$%:@\[\]^{}~#|]*/, 'keyword.constant'],

        // Standalone nil / t (not inside next/ten/count)
        [/(?<=^|[\s()])(?:nil|t)(?=$|[\s()])/, 'constant.language'],

        // Numbers (incl. .05)
        [
          /(?:0[xX][0-9a-fA-F]+)|(?:\d+\.\d*(?:[eE][+-]?\d+)?|\.\d+(?:[eE][+-]?\d+)?)|\d+(?:[eE][+-]?\d+)?/,
          'number',
        ],

        // Identifiers / symbols — classify ACT-R & CL vocabulary
        [
          /[a-zA-Z*][\w+\-<>/*&=.?!$%@^{}~|]*/,
          {
            cases: {
              '@modelForms': 'keyword',
              '@productionKeywords': 'keyword',
              '@lispSpecials': 'keyword',
              '@default': 'identifier',
            },
          },
        ],
      ],
      whitespace: [
        [/[ \t\r\n]+/, 'white'],
        [/#\|/, 'comment', '@blockComment'],
        [/;.*$/, 'comment'],
      ],
      blockComment: [
        [/[^|#]+/, 'comment'],
        [/\|#/, 'comment', '@pop'],
        [/[\|#]/, 'comment'],
      ],
      strings: [[/"/, 'string', '@stringBody']],
      stringBody: [
        [/\\./, 'string.escape'],
        [/"/, 'string', '@pop'],
        [/[^\\"]+/, 'string'],
      ],
    },
  },
};

contributionRegistry.registerContribution(MONACO_GRAMMARS, actrLispGrammar);
